### ISSUE TITLE
util lab grade script issues

### ISSUE THREAD

**Issue by ghost** [mit-pdos/xv6-riscv-fall19#4]
1. when I tested xargs function, I got this result.
![image](https://user-images.githubusercontent.com/25812494/65382784-950ed980-dd3e-11e9-8d33-adaa11694461.png)
I think it is right result.
2. But when I run `make grade`, I got some error like that
![image](https://user-images.githubusercontent.com/25812494/65382806-0d759a80-dd3f-11e9-8b84-c36c2c653a38.png)
3. So I test again like this
![image](https://user-images.githubusercontent.com/25812494/65382829-57f71700-dd3f-11e9-9baf-5c30758dfef5.png)
I find `DONE` print earlier than three `hello`. Maybe this caused grade error.
4. I try to fix this, but I failed. And I try to change the `test_xargs()` like that
![image](https://user-images.githubusercontent.com/25812494/65382903-f1262d80-dd3f-11e9-8a77-6203ad1964d2.png)
Then I run `make grade`, and get 100 points.
![image](https://user-images.githubusercontent.com/25812494/65382924-2894da00-dd40-11e9-9676-f80686f19d46.png)

Sorry for my poor English.
Hopefully get your respond. Thanks!
And my code repo is [here](https://github.com/makeztc/mit-os-lab)

**Comment by anishathalye** [comment]
I don't think this is a bug in the grading script.

One guess is that your xargs does not properly `wait()` until all children are done. This results in the "hello"s being interleaved with the DONE. The grader looks at the output before the DONE.

**Comment by ghost** [comment]
Yes，your guess is right. This is my bug. Thanks for your respond and help. Thank you.

**Comment by trantho1615** [comment]
can u guide me how to run make grade
